# Generated by Django 2.2.7 on 2019-11-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='bank_id',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
