# Generated by Django 2.2.7 on 2019-11-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0003_auto_20191119_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchinfo',
            name='bank_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='branchinfo',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='branchinfo',
            name='district',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='branchinfo',
            name='ifsc',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='branchinfo',
            name='state',
            field=models.CharField(max_length=150),
        ),
    ]
