# Generated by Django 2.2.7 on 2019-11-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0004_auto_20191119_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchinfo',
            name='ifsc',
            field=models.CharField(max_length=150),
        ),
    ]
